<div class="col-xs-10 col-sm-8 col-md-8 col-lg-8  col-xs-offset-1 col-sm-offset-2 col-md-offset-2 col-lg-offset-2">

   <div class="header-titulos">REGISTRO DE ALUMNO</div>

<form id="form_registro">
  
<div class="form-group ">
      <label class="">CEDULA</label>
      <input type="nombres" class="form-control" name="cedula" id="cedula" placeholder="CEDULA" >
     
  
  <div class="form-group">
    <label class="">USUARIO</label>
    <input type="text" class="form-control" name="loginr" id="loginr" placeholder="USUARIO">
  </div>

 
  
  <div class="form-group">
    <label class="">CONTRASEÑA</label>
      <input type="password" class="form-control" name="pass" id="pass" placeholder="CONTRASEÑA">
  </div>

  <div class="form-group">
    <label class="">COMFIRMAR</label>
   <input type="password" class="form-control" name="confirmar" id="confirmar" placeholder="CONTRASEÑA">
  </div>




   
  
<div class="form-group">
 <center>
      <button id="registrar_alumno" type="button" class="btn btn-primary">REGISTRAR</button>
      <a href="<?php echo BASE_URL;?>"> REGRESAR </a>
 </center>
  </div>

</form>
</div>





