
   <div class="col-xs-10 col-sm-8 col-md-8 col-lg-8  col-xs-offset-1 col-sm-offset-2 col-md-offset-2 col-lg-offset-2">

   <div class="header-titulos">REGISTRO DE PROFESOR</div>

<form id="form_registro">
  
<div class="form-group ">
      <label class="">CEDULA</label>
      <input type="text" class="form-control" name="cedula" id="cedula" placeholder="CEDULA" >
     
  </div> 
  <div class="form-group ">
      <label class="">NOMBRES</label>
      <input type="text" class="form-control" name="nombres" id="nombres" placeholder="NOMBRES" >
     
  </div>  
  <div class="form-group ">
      <label class="">APELLIDOS</label>
      <input type="text" class="form-control" name="apellidos" id="apellidos" placeholder="APELLIDOS" >
     
  </div>  

  
  <div class="form-group">
    <label class="">DIRECCIÓN</label>
    <input type="text" class="form-control" name="direccion" id="direccion" placeholder="DIRECCIÓN">
  </div>

  <div class="form-group">
    <label class="">TELEFONO</label>
    <input type="text" class="form-control" name="telefono" id="telefono" placeholder="TELEFONO">
   
  </div>

 <div class="form-group">
    <label class="">EMAIL</label>
    <input type="text" class="form-control" name="email" id="email" placeholder="EMAIL">
   
  </div>

   
  
  <div class="form-group">
    <label class="">USUARIO</label>
    <input type="text" class="form-control" name="loginr" id="loginr" placeholder="USUARIO">
  </div>

 
  
  <div class="form-group">
    <label class="">CONTRASEÑA</label>
      <input type="password" class="form-control" name="pass" id="pass"  placeholder="CONTRASEÑA">
  </div>

  <div class="form-group">
    <label class="">COMFIRMAR</label>
   <input type="password" class="form-control" name="confirmar" id="confirmar"  placeholder="CONTRASEÑA">
  </div>




   
  
<div class="form-group">
 <center>
      <button id="registrar" type="button" class="btn btn-primary">REGISTRAR</button>
      <a href="<?php echo BASE_URL;?>"> REGRESAR </a>
 </center>
  </div>

</form>
</div>












  




