    
      <div class="col-xs-12 col-sm-4  col-xs-offset-0 col-sm-offset-4 ">

      <div class="header-titulos">INICIAR SESIÓN</div>   


      <form class="" role="form" method="post" action="<?php echo BASE_URL?>login">
      <input type="hidden" value="1" name="enviar" />
      
        <input type="text" name="usuario" value="<?php if(isset($this->datos)) echo $this->datos['usuario']; ?>" class="form-control" placeholder="USUARIO" required autofocus>
        <input type="password" name="pass" class="form-control" placeholder="CONTRASEÑA" required>
       
        <button class="btn btn-lg btn-success btn-block" type="submit">INICIAR SESIÓN</button>
        
      </form>


      </div>
       