<div scroll="auto" class="col-xs-10 col-sm-10 col-md-10 col-lg-10  col-xs-offset-1 col-sm-offset-1 col-md-offset-1 col-lg-offset-1">
<div class="header-titulos">SISTEMA DE COLTROL <?php echo APP_NAME; ?> </div>




<article id='collace_opt'>
			<div id='capas_tras_up'>
			<div id="fondo_gris">
				<span class="glyphicon glyphicon-lock" aria-hidden="true"> PROVEEDOR
				</span>
			</div>
			</div>
			<div id='capas_tras_donw'>
				
				<div id="opt_" data-accion="agregar" data-controller="proveedor">
					<span class="glyphicon glyphicon-plus" aria-hidden="true"></span> <br/>
					<font>Agregar</font>
				</div>
				<div id="opt_" data-accion="gestionar" data-controller="proveedor">
					<span class="glyphicon glyphicon-th-list" aria-hidden="true"></span><br/>
					<font>Gestionar</font>
				</div>
				
				


			</div>
</article>

<article id='collace_opt'>
			<div id='capas_tras_up'>
				<div id="fondo_gris">
				<span class="glyphicon glyphicon-piggy-bank" aria-hidden="true"> BANCOS
				</span>
				</div>
			</div>
			<div id='capas_tras_donw' >
				<div id="opt_" data-accion="agregar" data-controller="banco">
					<span class="glyphicon glyphicon-plus" aria-hidden="true"></span> <br/>
					<font>Agregar</font>
				</div>
				<div id="opt_" data-accion="gestionar" data-controller="banco">
					<span class="glyphicon glyphicon-th-list" aria-hidden="true"></span><br/>
					<font>Gestionar</font>
				</div>
			</div>
</article>

<article id="texto_principal">
	
		<p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Cras quam velit, mollis in dolor bibendum, dictum varius erat. Pellentesque nec finibus nisi. Etiam pellentesque magna ut interdum molestie. Fusce blandit facilisis blandit. Phasellus tristique quis mauris sit amet aliquet. Proin non imperdiet urna. Nam euismod quam facilisis urna pretium, at aliquam libero lacinia. Mauris convallis ultricies nisl, quis pulvinar velit mattis et. Etiam maximus erat et ligula pharetra, non pharetra velit lacinia.</p>

</article>
<article id="menu_gestion">
	<center>
	<div id="x_gestion" data-controller="orden_de_pago">
	<div>orden de pago</div>
		<div><p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Cras quam velit, mollis in dolor bibendum, dictum varius erat. Pellentesque nec finibus nisi.</p></diV>
		<div><span class="glyphicon glyphicon-cog" arial-hidden="true"></span></diV>

	</div>
	<div id="x_gestion" data-controller="reportes">
		<div>reportes</div>
		<div><p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Cras quam velit, mollis in dolor bibendum, dictum varius erat. Pellentesque nec finibus nisi.</p></diV>
		<div><span class="glyphicon glyphicon-cog" arial-hidden="true"></span></diV>

	</div>
	</center>

</article>

</div>